/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DemoRouteRouteImport } from './routes/demo/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as homeRoutesRouteRouteImport } from './routes/(home)/routes/route'
import { Route as homeRoutesIndexRouteImport } from './routes/(home)/routes/index'
import { Route as homeRoutesRouteIdRouteRouteImport } from './routes/(home)/routes/$routeId/route'
import { Route as homeRoutesRouteIdSettingsRouteImport } from './routes/(home)/routes/$routeId/settings'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeRoutesRouteRoute = homeRoutesRouteRouteImport.update({
  id: '/(home)/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const homeRoutesIndexRoute = homeRoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeRoutesRouteRoute,
} as any)
const homeRoutesRouteIdRouteRoute = homeRoutesRouteIdRouteRouteImport.update({
  id: '/$routeId',
  path: '/$routeId',
  getParentRoute: () => homeRoutesRouteRoute,
} as any)
const homeRoutesRouteIdSettingsRoute =
  homeRoutesRouteIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => homeRoutesRouteIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/routes': typeof homeRoutesRouteRouteWithChildren
  '/routes/$routeId': typeof homeRoutesRouteIdRouteRouteWithChildren
  '/routes/': typeof homeRoutesIndexRoute
  '/routes/$routeId/settings': typeof homeRoutesRouteIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/routes/$routeId': typeof homeRoutesRouteIdRouteRouteWithChildren
  '/routes': typeof homeRoutesIndexRoute
  '/routes/$routeId/settings': typeof homeRoutesRouteIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/(home)/routes': typeof homeRoutesRouteRouteWithChildren
  '/(home)/routes/$routeId': typeof homeRoutesRouteIdRouteRouteWithChildren
  '/(home)/routes/': typeof homeRoutesIndexRoute
  '/(home)/routes/$routeId/settings': typeof homeRoutesRouteIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/sign-in'
    | '/sign-up'
    | '/routes'
    | '/routes/$routeId'
    | '/routes/'
    | '/routes/$routeId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/sign-in'
    | '/sign-up'
    | '/routes/$routeId'
    | '/routes'
    | '/routes/$routeId/settings'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/sign-in'
    | '/sign-up'
    | '/(home)/routes'
    | '/(home)/routes/$routeId'
    | '/(home)/routes/'
    | '/(home)/routes/$routeId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRouteRoute: typeof DemoRouteRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  homeRoutesRouteRoute: typeof homeRoutesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/routes': {
      id: '/(home)/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof homeRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/routes/': {
      id: '/(home)/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof homeRoutesIndexRouteImport
      parentRoute: typeof homeRoutesRouteRoute
    }
    '/(home)/routes/$routeId': {
      id: '/(home)/routes/$routeId'
      path: '/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof homeRoutesRouteIdRouteRouteImport
      parentRoute: typeof homeRoutesRouteRoute
    }
    '/(home)/routes/$routeId/settings': {
      id: '/(home)/routes/$routeId/settings'
      path: '/settings'
      fullPath: '/routes/$routeId/settings'
      preLoaderRoute: typeof homeRoutesRouteIdSettingsRouteImport
      parentRoute: typeof homeRoutesRouteIdRouteRoute
    }
  }
}

interface homeRoutesRouteIdRouteRouteChildren {
  homeRoutesRouteIdSettingsRoute: typeof homeRoutesRouteIdSettingsRoute
}

const homeRoutesRouteIdRouteRouteChildren: homeRoutesRouteIdRouteRouteChildren =
  {
    homeRoutesRouteIdSettingsRoute: homeRoutesRouteIdSettingsRoute,
  }

const homeRoutesRouteIdRouteRouteWithChildren =
  homeRoutesRouteIdRouteRoute._addFileChildren(
    homeRoutesRouteIdRouteRouteChildren,
  )

interface homeRoutesRouteRouteChildren {
  homeRoutesRouteIdRouteRoute: typeof homeRoutesRouteIdRouteRouteWithChildren
  homeRoutesIndexRoute: typeof homeRoutesIndexRoute
}

const homeRoutesRouteRouteChildren: homeRoutesRouteRouteChildren = {
  homeRoutesRouteIdRouteRoute: homeRoutesRouteIdRouteRouteWithChildren,
  homeRoutesIndexRoute: homeRoutesIndexRoute,
}

const homeRoutesRouteRouteWithChildren = homeRoutesRouteRoute._addFileChildren(
  homeRoutesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRouteRoute: DemoRouteRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  homeRoutesRouteRoute: homeRoutesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
